import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image';
import { ChangeEvent, useState } from 'react';
import Card from '../components/card';
import Layout from '../components/layout';
import { BASE_URL } from '../config';
import { SmiteGod } from '../models/smite.god';
import styles from '../styles/Home.module.css'

export interface HomeProps {
  smiteGods: SmiteGod[];
  roles: string[];
}

const Home: NextPage<HomeProps> = ({ smiteGods, roles }) => {
  const cardCount: number = 5;
  const defaultValue: Record<number, boolean> = {};
  for (let i = 0; i < cardCount; i++) {
    defaultValue[i] = false;
  }
  const [smiteGodCardMap, setSmiteGodCardMap] = useState<Record<number, boolean>>(defaultValue);
  const [role, setRole] = useState("Any");


  const randomizeAll = () => {
    const available = smiteGods.reduce((list: number[], smiteGod: SmiteGod, smiteGodIndex: number) => {
      const isValidRole: boolean = role === "Any" || smiteGod.Roles.includes(role);
      const isNotChosen: boolean = smiteGodCardMap[smiteGodIndex] === undefined;
      if (isValidRole && isNotChosen) {
        list.push(smiteGodIndex);
      }
      return list;
    }, []);

    const randomSmiteGodCardMap: Record<number, boolean> = {};
    for (let i = 0; i < cardCount; i++) {
      let randomIndex: number;
      let smiteGodIndex: number;
      do {
        randomIndex = Math.floor(Math.random() * available.length);
        smiteGodIndex = available[randomIndex];
      } while (randomSmiteGodCardMap[smiteGodIndex] !== undefined);
      randomSmiteGodCardMap[smiteGodIndex] = false;
    }
    setSmiteGodCardMap(randomSmiteGodCardMap);
  }

  const onChangeRole = (event: ChangeEvent<HTMLSelectElement>) => setRole(event.target.value);

  const flip = (smiteGodIndex: number) => setSmiteGodCardMap({ ...smiteGodCardMap, [smiteGodIndex]: true });

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.actions}>
        <div className={styles.left}>
          <select name="role" id="role" onChange={onChangeRole} defaultValue={role}>
            {roles.map((role: string) => (
              <option key={role} value={role}>{role}</option>
            ))}
          </select>
        </div>
        <div className={styles.right}>
          <button type="button" onClick={randomizeAll}>Randomize</button>
        </div>
      </div>
      <div className={styles.cards}>
        {Object.entries(smiteGodCardMap).map(([mapIndex, flipped]: [string, boolean], index: number) => {
          const smiteGodIndex: number = Number(mapIndex);
          const { Name, godCard_URL, Title, Pantheon}: SmiteGod = smiteGods[smiteGodIndex];
          return (
            <Card key={`${Name}-${smiteGodIndex}-${index}`} flipped={flipped} onClick={() => flip(smiteGodIndex)}>
              <Card.Front>
                <Image src="/hexagons.svg" alt="Hexagon Pattern SVG" layout="fill" objectFit="cover" draggable={false} />
              </Card.Front>
              <Card.Back>
                <Card.Background imageURL={godCard_URL}>
                  <div className={styles.content}>
                    <h1>{Name}</h1>
                    <p>{Title}</p>
                    <p>{Pantheon}</p>
                  </div>
                </Card.Background>
              </Card.Back>
            </Card>
          );
        })}
      </div>
    </Layout>
  );
}

export default Home

export async function getStaticProps() {
  const res = await fetch(`${BASE_URL}/api/smite/gods`);
  const smiteGods = await res.json();
  const roles = smiteGods.reduce((list: string[], smiteGod: SmiteGod) => {
    const roles = smiteGod.Roles.split(",").map((role: string) => role.trim());
    for (const role of roles) {
      if (!list.includes(role)) {
        list.push(role);
      }
    }
    return list;
  }, ["Any"]);
  return {
    props: {
      smiteGods,
      roles,
    },
  };
}
